[package]
name = "supafilex"
version = "0.1.0"
edition = "2021"

[dependencies]
mupdf = "0.5.0"
image = "0.24"
anyhow = "1.0"
tesseract-sys = "0.6.2"
leptonica-sys = "0.4.9"
reqwest = { version = "0.11", features = ["blocking"] }
